services:
  postgres:
    container_name: secret-postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=secret
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=secret
    ports:
      - "55432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
